"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const all_analysis_goods_by_date_added_1 = __importDefault(require("./all-analysis-goods-by-date-added"));
const all_diffs_1 = __importDefault(require("./all-diffs"));
const last_diff_1 = __importDefault(require("./last-diff"));
const products_count_1 = __importDefault(require("./products-count"));
const reports_1 = __importDefault(require("./reports"));
const total_uniq_products_count_1 = __importDefault(require("./total-uniq-products-count"));
const router = (0, express_1.Router)();
router.get("/last-diff", last_diff_1.default);
router.get("/reports", reports_1.default);
router.get("/all-diffs", all_diffs_1.default);
router.get("/all-analysis-goods-by-date-added", all_analysis_goods_by_date_added_1.default);
router.get("/products-count", products_count_1.default);
router.get("/total-uniq-products-count", total_uniq_products_count_1.default);
exports.default = router;
