"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const add_analysis_report_1 = __importDefault(require("./add-analysis-report"));
const add_new_price_list_1 = __importDefault(require("./add-new-price-list"));
const all_notification_users_1 = __importDefault(require("./all-notification-users"));
const all_price_lists_1 = __importDefault(require("./all-price-lists"));
const clear_cache_by_key_1 = __importDefault(require("./clear-cache-by-key"));
const delete_analysis_data_1 = __importDefault(require("./delete-analysis-data"));
const delete_analysis_data_by_date_1 = __importDefault(require("./delete-analysis-data-by-date"));
const delete_analysis_diff_1 = __importDefault(require("./delete-analysis-diff"));
const delete_analysis_diff_by_date_1 = __importDefault(require("./delete-analysis-diff-by-date"));
const delete_analysis_report_by_city_date_1 = __importDefault(require("./delete-analysis-report-by-city-date"));
const delete_last_price_list_1 = __importDefault(require("./delete-last-price-list"));
const insert_analysis_data_1 = __importDefault(require("./insert-analysis-data"));
const insert_analysis_diff_1 = __importDefault(require("./insert-analysis-diff"));
const update_users_favorites_1 = __importDefault(require("./update-users-favorites"));
const router = (0, express_1.Router)();
router.get("/all-price-lists", all_price_lists_1.default);
router.post("/delete-last-price-list", delete_last_price_list_1.default);
router.post("/add-new-price-list", add_new_price_list_1.default);
router.post("/insert-analysis-data", insert_analysis_data_1.default);
router.post("/delete-analysis-data", delete_analysis_data_1.default);
router.post("/delete-analysis-data-by-date", delete_analysis_data_by_date_1.default);
router.post("/insert-analysis-diff", insert_analysis_diff_1.default);
router.post("/delete-analysis-diff", delete_analysis_diff_1.default);
router.post("/delete-analysis-diff-by-date", delete_analysis_diff_by_date_1.default);
router.post("/add-analysis-report", add_analysis_report_1.default);
router.post("/delete-analysis-report-by-city-date", delete_analysis_report_by_city_date_1.default);
router.get("/all-notification-users", all_notification_users_1.default);
router.post("/update-users-favorites", update_users_favorites_1.default);
router.post("/clear-cache-by-key", clear_cache_by_key_1.default);
exports.default = router;
